name: "Run Benchmark"
description: "Runs a framework on a task"

inputs:
  framework:
    description: 'Framework to run'
    default: 'constantpredictor'
    required: true
  task:
    description: 'Task to run the framework on'
    default: 'kc1'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run Task
      run: |
        python runbenchmark.py ${{ inputs.framework }} validation test -f 0 -t ${{ inputs.task }}
      shell: bash
