language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - cd tests
  - pytest
