inputs:
  framework:
    description: 'Framework to run'
    default: 'constantpredictor'
  task:
    description: 'Task to run the framework on'
    default: 'kc1'

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task
      run: |
        python runbenchmark.py ${{ inputs.framework }} validation test -f 0 -t ${{ inputs.task }}