name: Tests

on: pull_request

jobs:
  changed-frameworks:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.diff.outputs.changed }}
    steps:
    - uses: actions/checkout@v2
    - name: store changed frameworks
      id: diff
      run: echo "::set-output name=changed::`git diff --name-only HEAD..$GITHUB_BASE_REF | grep -o -i 'frameworks/.*/' | uniq | sed -e 's/frameworks//' -e 's/\///'`"

  echo-output:
    runs-on: ubuntu-latest
    needs: changed-frameworks
    steps:
    - run: echo ${{needs.changed-frameworks.outputs.output1}}

  autoxgboost:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        framework: [autoxgboost]  # autogluon, gama, h2oautoml, mlplan, tpot, autosklearn,
        task: [bioresponse, dresses-sales, eucalyptus, internet-advertisements, micro-mass, kc1, APSFailure]
      fail-fast:  true  # not sure about this one, but considering the big workload it might be nicer

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          pip-
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task
      run: |
        python runbenchmark.py ${{ matrix.framework }} validation test -f 0 -t ${{ matrix.task }}

  autosklearn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        framework: [autosklearn]
        task: [bioresponse, dresses-sales, eucalyptus, internet-advertisements, micro-mass, kc1, APSFailure]
      fail-fast:  true  # not sure about this one, but considering the big workload it might be nicer

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: ./.github/actions/runbenchmark
      with:
        framework: autosklearn
        task: ${{ matrix.task }}
