name: Run Specific Frameworks

# run either if *only* frameworks are edited, or always if the workflow or action is edited.
on:
  pull_request:
    paths:
      - 'frameworks/**'
      - '!frameworks/shared/**'
      - '!amlb/**'
      - '!frameworks/shared/**'
      - '!runbenchmark.py'
      - '!requirements.txt'
      - '.github/workflows/run_frameworks.yml'
      - '.github/actions/runbenchmark/action.yml'


jobs:
  framework_changes:
    name: Detect Changed AutoML Frameworks
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.frameworks-diff.outputs.frameworks }}
    steps:
    - uses: actions/checkout@v2
    - name: pull base branch
      run: |
        git fetch --all
        git checkout -b $GITHUB_BASE_REF origin/$GITHUB_BASE_REF
        git checkout $GITHUB_HEAD_REF
    - name: store changed frameworks
      id: frameworks-diff
      run: echo "::set-output name=frameworks::`git diff --name-only HEAD..$GITHUB_BASE_REF | grep -o -i -P 'frameworks/(?!shared).*/' | uniq | sed -e 's/frameworks//' -e 's/\///g'`"


  run_frameworks:
    name: Run ${{ matrix.framework }} on ${{ matrix.task }}
    runs-on: ubuntu-latest
    needs: framework_changes
    strategy:
      matrix:
        framework: [autoxgboost, autogluon, gama, h2oautoml, mlplan, tpot, autosklearn]
        task: [bioresponse, dresses-sales, eucalyptus, internet-advertisements, micro-mass, kc1, APSFailure]
      fail-fast:  true

    steps:
      - name: Debug Echo
        run: |
          echo ${{ needs.framework_changes.outputs.output1 }}
          echo ${{ matrix.framework }}
      - name: Cancel if ${{ matrix.framework }} not changed
        if: contains('what', 'is going on')
        run: echo What is going on?
      - name: Cancel if ${{ matrix.framework }} not changed
        if: contains(needs.framework_changes.outputs.output1, matrix.framework)
        run: echo ${{ matrix.framework }} is a substring of ${{ needs.framework_changes.outputs.output1 }}
      - uses: andymckay/cancel-action@0.2
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run benchmark
        uses: ./.github/actions/runbenchmark
        with:
          framework: ${{ matrix.framework }}
          task: ${{ matrix.task }}