name: Run Specific Frameworks

# run either if *only* frameworks are edited, or always if the workflow or action is edited.
on:
  pull_request:
    paths:
      - 'frameworks/**'
      - '!frameworks/shared/**'
      - '!amlb/**'
      - '!frameworks/shared/**'
      - '!runbenchmark.py'
      - '!requirements.txt'
      - '.github/workflows/run_frameworks.yml'
      - '.github/actions/runbenchmark/action.yml'


jobs:
  framework_changes:
    name: Detect Changed AutoML Frameworks
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.frameworks-diff.outputs.frameworks }}
    steps:
    - uses: actions/checkout@v2
    - name: pull base branch
      run: |
        git fetch --all
        git checkout -b $GITHUB_BASE_REF origin/$GITHUB_BASE_REF
        git checkout $GITHUB_HEAD_REF
    - name: store changed frameworks
      id: frameworks-diff
      run: echo "::set-output name=frameworks::`git diff --name-only HEAD..$GITHUB_BASE_REF | grep -o -i -P 'frameworks/(?!shared).*/' | uniq | sed -e 's/frameworks//' -e 's/\///g'`"

  autoxgboost:
    needs: framework_changes
    if: contains(needs.framework_changes.outputs.output1, 'autoxgboost')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        framework: [autoxgboost]  # autogluon, gama, h2oautoml, mlplan, tpot, autosklearn,
        task: [bioresponse, dresses-sales, eucalyptus, internet-advertisements, micro-mass, kc1, APSFailure]
      fail-fast:  true  # not sure about this one, but considering the big workload it might be nicer

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          pip-
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task
      run: |
        python runbenchmark.py ${{ matrix.framework }} validation test -f 0 -t ${{ matrix.task }}

  autosklearn:
    # steps.changed-my-tools.outputs.changed == 'true'
    # contains(github.ref, 'develop')
    needs: framework_changes
    if: contains(needs.framework_changes.outputs.output1, 'autosklearn')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        framework: [autosklearn]
        task: [bioresponse, dresses-sales, eucalyptus, internet-advertisements, micro-mass, kc1, APSFailure]
      fail-fast:  true  # not sure about this one, but considering the big workload it might be nicer

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: ./.github/actions/runbenchmark
      with:
        framework: autosklearn
        task: ${{ matrix.task }}
